export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    FILTER_PRODUCTS_BY_CATEGORY:" FILTER_PRODUCTS_BY_CATEGORY",
  
// cartActions
      ADD_TO_CART:"ADD_TO_CART",
      REMOVE_FROM_CART:'REMOVE_FROM_CART',
      DECREASE:'DECREASE',
      INCREASE:'INCREASE',
      CLEARCART:"CLEARCART",
      InCREASEITEMPRICE:'InCREASEITEMPRICE'

  };
